import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);
		// Initailizes a random numbers generator with the given seed value
        Random generator = new Random(seed);  
		int sum2 = 0;
		int sum3 = 0;
		int sum4 = 0;
		int allsum = 0;
		for(int i = 0; i<T; i++){
		boolean child = true;
		int sum = 0;
		double x = generator.nextDouble();
		if (x<0.5) 
		{
			sum++;
		} else {
			sum++;
			child = false;
		       } 
		boolean kid = child;
		while (kid==child) {
			x = Math.random();
			if (x<0.5) 
		{
				sum++;
				kid = true;
		} else {
			sum++;
			kid = false;
		       } 
		}
		if ( sum == 2) {
			sum2++;
		} else if (sum == 3) {
			sum3++;
		} else {
			sum4++;
		}	
		allsum=allsum+sum;
		}
		double avg=(double)allsum/T;
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + sum2);
		System.out.println("Number of families with 3 children: " + sum3);
		System.out.println("Number of families with 4 or more children: " + sum4);

		if (sum2>sum3&&sum2>sum4) {
			System.out.println("The most common number of children is 2.");
		}
		else if (sum3>sum4&&sum3>sum2) {
			System.out.println("The most common number of children is 3.");
		}
		else {
			System.out.println("The most common number of children is 4.");
		}
		//// In the previous version of this program, you used a statement like:
		//// double rnd = Math.random();
		//// Where "rnd" is the variable that stores the generated random value.
		//// In this version of the program, replace this statement with:
		//// double rnd = generator.nextDouble();
		//// This statement will generate a random value in the range [0,1),
		//// just like you had in the previous version, except that the 
		//// randomization will be based on the given seed.
		//// This is the only change that you have to do in the program.
		    
	}
}
